########################
# Dockerfile_test
########################
# 1. Base image
FROM continuumio/miniconda3

# 2. Put everything under /app
WORKDIR /app
COPY . /app

# 3. Create the conda environment
#    (expects metadmin_env.yml to be at repo root)
RUN conda env create -f metadmin_env.yml

# 4. Activate the env for every subsequent RUN / CMD
SHELL ["conda", "run", "-n", "metadmin_env", "/bin/bash", "-c"]

# 5. Make sure the OpenAI client is at the version
#    that works for *all* scripts (1.93.0)
RUN pip install --upgrade pip && \
    pip install openai==1.93.0

# 6. Default to an interactive shell
CMD ["bash"]

